name: code_forge
description: "A sophisticated code editor package with AI completion, LSP support, syntax highlighting, and advanced editing capabilities."
version: 3.0.0
homepage: https://github.com/heckmon/code_forge

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter  
  http: ^1.6.0
  markdown_widget: ^2.3.2+8
  meta: ^1.17.0
  re_highlight: ^0.0.3
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Method
      fonts:
        - asset: assets/icons/method.ttf
    - family: Variable
      fonts:
        - asset: assets/icons/variable.ttf
    - family: Class
      fonts:
        - asset: assets/icons/class.ttf
    - family: Enum
      fonts:
        - asset: assets/icons/enum.ttf
    - family: KeyWord
      fonts:
        - asset: assets/icons/keyword.ttf
    - family: Reference
      fonts:
        - asset: assets/icons/reference.ttf
    - family: Constant
      fonts:
        - asset: assets/icons/constant.ttf
    - family: Struct
      fonts:
        - asset: assets/icons/struct.ttf
    - family: Event
      fonts:
        - asset: assets/icons/event.ttf
    - family: Operator
      fonts:
        - asset: assets/icons/operator.ttf
    - family: Parameter
      fonts:
        - asset: assets/icons/parameter.ttf
    - family: Snippet
      fonts:
        - asset: assets/icons/snippet.ttf
    - family: Interface
      fonts:
        - asset: assets/icons/interface.ttf
    - family: Field
      fonts:
        - asset: assets/icons/field.ttf
